trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
  - job: SecondJob
    steps: 
    - bash: echo Build SecondJob
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourceDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
# - stage: DevDeploy
#   dependsOn: Build
#   jobs: 
#   - job: DevDeployJob
#     steps:
#     - bash: echo DevDeployJob
# - stage: QADeploy
#   dependsOn: Build
#   jobs:
#   - job: QADeployJob
#     steps: 
#     - bash: echo QADeployJob
# - stage: ProdDeploy
#   dependsOn:
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: ProdDeployJob
#     steps:
#     - bash: echo ProdDployJob