trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: Docker@2
  inputs:
    containerRegistry: 'emekadocker-hub'
    repository: 'emekadocker/currency-exchange-devops'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'manifests'
    publishLocation: 'Container'
  
  #publish
stage:
- stage: Deploy
  displayName: Deploy image
  jobs: 
  - job: Deploy
  displayName: Deploy
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  #Download image
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'manifests'
      itemPattern: '**/*.yaml'
      targetPath: '$(System.ArtifactsDirectory)'

  - task: KubernetesManifest@1
    inputs:
      action: 'deploy'
      connectionType: 'kubernetesServiceConnection'
      kubernetesServiceConnection: 'kube-connect'
      namespace: 'default'
      manifests: '$(System.ArtifactsDirectory)/deployment.yaml'
      containers: 'emekadocker/currency-exchange-devops:$(tag)'

