# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
jobs:
  - job: Terraform
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UseTerraform@0
        inputs:
          terraformVersion: 'latest'  # Or specify a version like '1.3.0'
      
      - script: |
          terraform --version  # Check if Terraform is installed
          terraform init
          terraform plan
        displayName: 'Run Terraform'